services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\GoogleMapsBundle\:
    resource: '../src/{Command,Controller,EventListener,EventSubscriber,Security,Util}/*'
    exclude: '../src/EventListener/{MapRendererListener.php,ApiRenderListener.php}'

  HeimrichHannot\GoogleMapsBundle\Manager\:
    resource: '../src/Manager/*'
    shared: false

  huh.google_maps.map_manager:
    alias: HeimrichHannot\GoogleMapsBundle\Manager\MapManager
    public: true

  huh.google_maps.overlay_manager:
    alias: HeimrichHannot\GoogleMapsBundle\Manager\OverlayManager
    public: true

  HeimrichHannot\GoogleMapsBundle\Collection\MapCollection: ~

  huh.google_maps.data_container.google_map:
    class: HeimrichHannot\GoogleMapsBundle\EventListener\DataContainer\GoogleMapListener
    public: true

  huh.google_maps.data_container.google_map_overlay:
    class: HeimrichHannot\GoogleMapsBundle\EventListener\DataContainer\OverlayListener
    public: true

  huh.google_maps.data_container.content:
    class: HeimrichHannot\GoogleMapsBundle\EventListener\DataContainer\ContentListener
    public: true

  huh.google_maps.data_container.map_wizard:
    class: HeimrichHannot\GoogleMapsBundle\EventListener\DataContainer\MapWizardListener
    public: true

  huh.google_maps.data_container.module:
    class: HeimrichHannot\GoogleMapsBundle\EventListener\DataContainer\ModuleListener
    public: true

  huh.google_maps.service.elevation:
    class: HeimrichHannot\GoogleMapsBundle\Service\ElevationService
    public: true

  huh.google_maps.utils.dca:
    alias: HeimrichHannot\GoogleMapsBundle\Util\DcaUtil
    public: true

  huh.google_maps.twig.extension:
    class: HeimrichHannot\GoogleMapsBundle\Twig\Extension
    tags:
      - { name: twig.extension }
    arguments:
      - "@huh.google_maps.map_manager"